# Generated by Django 4.0.2 on 2022-02-23 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Typeabo',
            fields=[
                ('refecence', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('idclient', models.ForeignKey(db_column='idClient', on_delete=django.db.models.deletion.DO_NOTHING, to='gestionApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idservice', models.AutoField(db_column='idService', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('idclient', models.ForeignKey(db_column='idClient', on_delete=django.db.models.deletion.DO_NOTHING, to='gestionApp.client')),
            ],
        ),
    ]
